### ISSUE TITLE
eegRDM method = euclidean gives NaN

### ISSUE THREAD

**Issue by ghost** [neurora/NeuroRA#6]
When trying to calculate eeg RDM, using correlation gives me good and valid results. However, changing the method to 'euclidean' only gives me NaN's. Is this a bug?

**Comment by ZitongLu1996** [comment]
> When trying to calculate eeg RDM, using correlation gives me good and valid results. However, changing the method to 'euclidean' only gives me NaN's. Is this a bug?

Thanks for letting me know! I will check it later and give you feedback!

**Comment by ZitongLu1996** [comment]
> > When trying to calculate eeg RDM, using correlation gives me good and valid results. However, changing the method to 'euclidean' only gives me NaN's. Is this a bug?
> 
> Thanks for letting me know! I will check it later and give you feedback!

In the new version 1.1.6.3, I solved this bug! You can upgrade NeuroRA by 'pip install --upgrade neurora'.

Thanks for your suggestions!
